// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/al0-social/TwitterCover.tsx": () => import("../components/mockups/al0-social/TwitterCover.tsx"),
  "./components/mockups/al0-social/TwitterProfile.tsx": () => import("../components/mockups/al0-social/TwitterProfile.tsx"),
  "./components/mockups/og-cards/Centered.tsx": () => import("../components/mockups/og-cards/Centered.tsx"),
  "./components/mockups/og-cards/LeftAccent.tsx": () => import("../components/mockups/og-cards/LeftAccent.tsx"),
  "./components/mockups/og-cards/Split.tsx": () => import("../components/mockups/og-cards/Split.tsx"),
  "./components/mockups/al0-logos/Bracket.tsx": () => import("../components/mockups/al0-logos/Bracket.tsx"),
  "./components/mockups/al0-logos/Circuit.tsx": () => import("../components/mockups/al0-logos/Circuit.tsx"),
  "./components/mockups/al0-logos/Layers.tsx": () => import("../components/mockups/al0-logos/Layers.tsx"),
  "./components/mockups/al0-logos/Typographic.tsx": () => import("../components/mockups/al0-logos/Typographic.tsx")
};
